show databases;
describe customer;
select * from customer limit 5;
ALTER TABLE customer
RENAME COLUMN `purchase_amount` TO purchase_amount;
-- Q1. What is the total revenue generated by male vs. female customers?
Select gender, sum(purchase_amount) as revenue
from customer
group by gender;

-- Q2. Which customers used a discount but still spent more than the average purchase amount? 
select customer_id, purchase_amount
from customer
where discount_applied='yes' and purchase_amount >=(select avg(purchase_amount) from customer);

-- Q3. Which are the top 5 products with the highest average review rating?
Select item_purchased, round(avg(review_rating), 2) as "Highest_review"
from customer
group by item_purchased
order by Highest_review desc
limit 5;

# Q4. Compare the average Purchase Amounts between Standard and Express Shipping.
Select shipping_type, avg(purchase_amount)
from customer 
where shipping_type in ('Standard','Express')
group by shipping_type;

-- Q5. Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers.
Select subscription_status,
count(customer_id) as "Total_customers",
round(Avg(purchase_amount),2) as "Avg_purchase_amount",
round(sum(purchase_amount),2) as "Total_revinew"
from customer
group by subscription_status
order by Total_revinew ;

-- Q6. Which 5 products have the highest percentage of purchases with discounts applied?

SELECT item_purchased,
       ROUND(
           (SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END)
           / COUNT(*)) * 100,
           2) AS discount_percentage
FROM customer
GROUP BY item_purchased
ORDER BY discount_percentage DESC
LIMIT 5;

-- Q7. Segment customers into New, Returning, and Loyal based on their total number of previous purchases, and show the count of each segment.
with customer_type as(
select customer_id, previous_purchases,
      case 
           when previous_purchases= 1 then 'New'
           when previous_purchases between 1 and 10 then 'Returning'
           else 'Loyal'
           end as 'customer_segment'
           from customer
          
           )
select customer_segment,  count(*) as Total_customers
from customer_type
group by customer_segment;

-- or

select 
     case
           when previous_purchases= 1 then 'New'
           when previous_purchases between 1 and 10 then 'Returning'
           else 'Loyal'
           end as customer_segment,
           count(*) as total_customer
           from customer
           group by customer_segment;

-- Q8. What are the top 3 most purchased products within each category? 
WITH item_counts AS (
    SELECT category,
           item_purchased,
           COUNT(customer_id) AS total_orders,
           ROW_NUMBER() OVER (PARTITION BY category ORDER BY COUNT(customer_id) DESC) AS item_rank
    FROM customer
    GROUP BY category, item_purchased
)
SELECT item_rank,category, item_purchased, total_orders
FROM item_counts
WHERE item_rank <=3;

-- Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
select subscription_status,
 count(customer_id) as Repeat_buyers
from customer 
where previous_purchases> 5
group by subscription_status;

-- Q10. What is the revenue contribution of each age group? 
Select age_group, sum(purchase_amount) as 'Total_revenue'
from customer
group by age_group
order by Total_revenue desc;
